#!/usr/bin/env python3
"""
Apply reviewed-safe jurisprudence metadata enrichment to the website catalog.

Inputs are generated by:
  /Users/lszoszk/Desktop/AI/HURIDOCS/App/pipeline/extract_jurisprudence_metadata.py

This script intentionally applies only safe display-name changes. Review-needed
name conflicts remain in the local review queue and are not published.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent
DEFAULT_INFO = ROOT / 'mysite_pythonanywhere' / 'jurisprudence_info.json'
DEFAULT_ENRICHED = Path('/Users/lszoszk/Desktop/AI/HURIDOCS/App/output/jurisprudence_metadata_enriched.jsonl')
DEFAULT_CANDIDATES = Path('/Users/lszoszk/Desktop/AI/HURIDOCS/App/output/jurisprudence_case_name_candidates.json')


def read_json(path: Path):
    with path.open(encoding='utf-8') as f:
        return json.load(f)


def write_json(path: Path, data) -> None:
    with path.open('w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write('\n')


def read_jsonl(path: Path) -> list[dict]:
    rows = []
    with path.open(encoding='utf-8') as f:
        for line in f:
            if line.strip():
                rows.append(json.loads(line))
    return rows


def nonempty(value):
    return value not in (None, '', [], {})


def clean_issue_names(row: dict) -> set[str]:
    return {issue.get('issue') for issue in row.get('metadataIssues') or [] if issue.get('issue')}


def publishable_state_party(row: dict) -> str | None:
    issues = clean_issue_names(row)
    if 'state_party_malformed' in issues or 'country_conflict' in issues:
        return None
    value = (row.get('metadataRaw') or {}).get('stateParty')
    if isinstance(value, str) and value.strip():
        return value.strip()
    return None


def metadata_payload(row: dict) -> dict:
    raw = row.get('metadataRaw') or {}
    norm = row.get('metadataNormalized') or {}
    sources = row.get('metadataSources') or {}
    payload = {}

    simple_raw_fields = [
        'submittedBy',
        'allegedVictims',
        'documentReferences',
    ]
    for field in simple_raw_fields:
        if nonempty(raw.get(field)):
            payload[field] = raw[field]

    for field in [
        'communicationDate',
        'adoptionDate',
        'subjectMatter',
        'proceduralIssues',
        'substantiveIssues',
        'rulesReferenced',
        'interimMeasuresMentioned',
    ]:
        if nonempty(norm.get(field)):
            payload[field] = norm[field]

    for field, out_field in [
        ('covenantArticles', 'covenantArticlesParsed'),
        ('conventionArticles', 'conventionArticlesParsed'),
        ('optionalProtocolArticles', 'optionalProtocolArticlesParsed'),
    ]:
        if nonempty(norm.get(field)):
            payload[out_field] = norm[field]
            if nonempty(raw.get(field)):
                payload[field] = raw[field]

    state_party = publishable_state_party(row)
    if state_party:
        payload['stateParty'] = state_party

    if nonempty(row.get('submittedByClean')):
        payload['submittedByClean'] = row['submittedByClean']
    if nonempty(row.get('representation')):
        payload['representation'] = row['representation']
    if nonempty(row.get('caseName')):
        payload['caseName'] = row['caseName']
        payload['caseNameSource'] = row.get('caseNameSource')
        payload['caseNameConfidence'] = row.get('caseNameConfidence')

    if nonempty(row.get('metadataConfidence')):
        payload['metadataConfidence'] = row['metadataConfidence']
    if sources:
        payload['metadataSources'] = sources

    if row.get('minnesota'):
        payload['externalNameAuthority'] = {
            'source': 'University of Minnesota Human Rights Library',
            **{k: v for k, v in row['minnesota'].items() if nonempty(v)},
        }

    return {k: v for k, v in payload.items() if nonempty(v)}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--info', type=Path, default=DEFAULT_INFO)
    parser.add_argument('--enriched', type=Path, default=DEFAULT_ENRICHED)
    parser.add_argument('--candidates', type=Path, default=DEFAULT_CANDIDATES)
    parser.add_argument('--dry-run', action='store_true')
    args = parser.parse_args()

    docs = read_json(args.info)
    enriched = {row['docId']: row for row in read_jsonl(args.enriched)}
    candidates = read_json(args.candidates)
    auto_safe_names = {
        row['docId']: row
        for row in candidates.get('candidates', [])
        if row.get('autoSafe') and row.get('candidateName')
    }

    changed_names = 0
    enriched_docs = 0
    for doc in docs:
        doc_id = doc.get('docId')
        row = enriched.get(doc_id)
        if not row:
            continue
        payload = metadata_payload(row)
        for key, value in payload.items():
            doc[key] = value
        enriched_docs += 1

        candidate = auto_safe_names.get(doc_id)
        if candidate:
            new_name = candidate['candidateName'].strip()
            old_name = (doc.get('name') or '').strip()
            if new_name and new_name != old_name:
                doc.setdefault('originalName', old_name)
                doc.setdefault('originalTitle', doc.get('title'))
                doc['name'] = new_name
                doc['nameShort'] = new_name
                doc['title'] = new_name
                doc['nameSource'] = candidate.get('caseNameSource')
                doc['nameConfidence'] = candidate.get('caseNameConfidence')
                changed_names += 1

    if not args.dry_run:
        write_json(args.info, docs)

    print(json.dumps({
        'documents': len(docs),
        'enrichedDocs': enriched_docs,
        'autoSafeNameChanges': changed_names,
        'dryRun': args.dry_run,
    }, ensure_ascii=False, indent=2))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
