#!/usr/bin/env python3
"""
Drop metadata-as-paragraph rows from the JUR shards under docs/jur/shards/.

Background
----------
The OHCHR-JURIS PDF extractor used in the v19.47 batch emitted the
case-header metadata fields ("Communication submitted by:", "Alleged
victim:", "State party:", "Date of communication:", "Substantive
issue:", "Procedural issue:", "Subject matter:", "Date of adoption of
decision:", "Document references:", "Articles of the Covenant",
"Article of the Optional Protocol") as separate paragraph rows in the
corpus. They render as polluted body text in the document reader and
also surface in search results — but every one of these values is
already stored as a structured field on the document record (the
dossier renders them from there).

This script drops those paragraphs from the JUR shards. Idempotent.

Audit (pre-clean):
  - 339 cases affected
  - 1,591 metadata-as-paragraph rows
  - 327 of the 339 cases are short (≤12 paragraphs total) where most
    of the document is metadata noise and only ~1-3 paragraphs carry
    real content.

We also drop a few related stub patterns that share the same root
cause:
  - bare month-year date stubs at the document head ("August 2024")
  - the formal title line ("Decision adopted by the Committee under
    the Optional Protocol, concerning communication No. NNNN/YYYY")
  - "Communication No. NNNN/YYYY" stubs
  - the "on civil and political rights" page-header crumb
  - bare session-date stubs ("October–2 November 2007")

Run
----
    python3 _docs_internal/sanitize_metadata_paragraphs.py            # dry-run
    python3 _docs_internal/sanitize_metadata_paragraphs.py --apply    # write

After --apply, runtime renumbering: paragraphs keep their original
`n` (which may now have gaps) and `idx` (which is regenerated by the
app on load). The reader handles missing `n` gracefully; gaps are
preferable to renumbering, since paragraph IDs (`<docId>-<NNNN>`)
must remain stable for bookmarks/permalinks.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SHARDS = REPO / "docs" / "jur" / "shards"

# Field-prefix patterns. Each must match the START of a (stripped) paragraph.
# Case-insensitive on the key, but leave the body alone.
META_KV_PATTERNS = [
    re.compile(r"^Communication submitted by\s*:", re.IGNORECASE),
    re.compile(r"^Submitted by\s*:", re.IGNORECASE),
    re.compile(r"^Alleged victim", re.IGNORECASE),
    re.compile(r"^State [Pp]arty\s*:", re.IGNORECASE),
    re.compile(r"^Dates? of communication\s*:", re.IGNORECASE),
    re.compile(r"^Date of adoption of decision", re.IGNORECASE),
    re.compile(r"^Date of adoption of [Vv]iews", re.IGNORECASE),
    re.compile(r"^Subject matter", re.IGNORECASE),
    re.compile(r"^Procedural issues?", re.IGNORECASE),
    re.compile(r"^Substantive issues?", re.IGNORECASE),
    re.compile(r"^Document references?\s*:", re.IGNORECASE),
    re.compile(r"^Articles? of the Covenant", re.IGNORECASE),
    re.compile(r"^Articles? of the (?:Optional Protocol|Convention)", re.IGNORECASE),
]

# Title-line and page-header stubs.
STUB_PATTERNS = [
    # "Decision adopted by the Committee under the Optional Protocol, concerning communication No. 4342/2023*, **"
    re.compile(
        r"^(Decision|Views) adopted by the Committee\b.*"
        r"(communication|case) No\.\s*\d+/\d+",
        re.IGNORECASE,
    ),
    # "Communication No. 4342/2023" (sometimes appears alone after a date)
    re.compile(r"^Communication No\.\s*\d+/\d+\s*$", re.IGNORECASE),
    # bare month-year date: "August 2024", "January 2025"
    re.compile(
        r"^(January|February|March|April|May|June|July|August|"
        r"September|October|November|December)\s+\d{4}\s*$",
        re.IGNORECASE,
    ),
    # session date span: "October–2 November 2007", "12–30 March 2018"
    re.compile(
        r"^\d{0,2}\s*(January|February|March|April|May|June|July|August|"
        r"September|October|November|December)\s*[–-]?\s*\d{1,2}?\s*"
        r"(January|February|March|April|May|June|July|August|"
        r"September|October|November|December)?\s*\d{4}\s*$",
        re.IGNORECASE,
    ),
    # page-header crumbs
    re.compile(r"^on civil and political rights\s*$", re.IGNORECASE),
    re.compile(r"^on the elimination of (?:racial )?discrimination(?: against women)?\s*$", re.IGNORECASE),
    # generic "Annex"-type stubs that show up at the end of the metadata block
    re.compile(r"^Annex\s*[IVX]+\s*$", re.IGNORECASE),
]


def is_metadata(text: str) -> bool:
    t = (text or "").strip()
    if not t:
        return True  # also drop empty
    for p in META_KV_PATTERNS:
        if p.match(t):
            return True
    for p in STUB_PATTERNS:
        if p.match(t):
            return True
    return False


def process_shard(path: Path, apply: bool) -> tuple[int, int]:
    """Return (paras_dropped, docs_touched)."""
    with path.open() as f:
        data = json.load(f)
    rows = data if isinstance(data, list) else data.get("paragraphs", [])

    kept = []
    dropped_count = 0
    touched_docs = set()
    for p in rows:
        text = p.get("text", "")
        if is_metadata(text):
            dropped_count += 1
            touched_docs.add(p.get("docId", ""))
            continue
        kept.append(p)

    if dropped_count and apply:
        if isinstance(data, list):
            data = kept
        else:
            data["paragraphs"] = kept
        with path.open("w") as f:
            json.dump(data, f, ensure_ascii=False, separators=(",", ":"))
            f.write("\n")
    return dropped_count, len(touched_docs)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--apply", action="store_true", help="Write changes back to disk.")
    args = ap.parse_args()

    print(f"Sanitising metadata-as-paragraph rows from {SHARDS.relative_to(REPO)}/")
    print(f"  mode: {'APPLY' if args.apply else 'dry-run'}")

    total_dropped = 0
    total_docs = set()
    per_shard = []
    for shard in sorted(SHARDS.iterdir()):
        if not shard.suffix == ".json":
            continue
        dropped, docs = process_shard(shard, args.apply)
        if dropped:
            per_shard.append((shard.name, dropped, docs))
        total_dropped += dropped

    for name, n, d in per_shard:
        print(f"  {name:<40s}  {n:>4d} paragraphs across {d:>4d} doc(s)")
    print(f"\nTotal: {total_dropped:,} paragraphs dropped")
    if not args.apply and total_dropped:
        print("Re-run with --apply to write the changes.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
